### PR TITLE
feat: Update to use pnpm

### PR DESCRIPTION
**Pull request by MorganDilling**

### CODE REVIEW

**Comment by MorganDilling** [comment]
Meant to make pull request on own fork.

**Comment by ghostdevv** [comment]
@MorganDilling We also prefer pnpm but there were some issues with electron that prevented us from using it, it may be worth seeing if those are fixed and then we could accept a pr here for pnpm

**Comment by MorganDilling** [comment]
@ghostdevv The issue I believe was just the build/dev scripts were using npm instead of pnpm and I think that was the only issue as far as I could tell. It would be opinionated though to make the change and would be a breaking change so it could be quite controversial.

**Comment by ghostdevv** [comment]
@MorganDilling I can't quite remember the issues with pnpm maybe @FractalHQ might, but it was something with the electron build system

**Comment by braebo** [comment]
I'm happy to let people choose their own package manager.  Npm is the safest bet, and @MorganDilling makes a good point about changing the default.  People like us will always easily replace npm with pnpm out of habit, but users who don't have pnpm installed will be inconvenienced.  If we waste peoples time, we're no better than npm 😜

Plus, if we really wanted to be elitist and impose our objectively superior tool choices on others, then this repo would be re-written in typescript... or even better, changed to `sveltekit-tauri` 😅

**Pull request closed without merging**
